### ISSUE TITLE
[minor, ed’s discretion, nit-picky, sorry] Repeated “Accessibility, Usability and Inclusion”

### ISSUE THREAD

**Issue by yatil** [w3c/wai-inclusion#28]
> # Accessibility, Usability, and Inclusion
> Accessibility, usability, and inclusion are closely related aspects in creating a web that works for everyone.

I don’t particularly like how the heading is repeated, but I don’t have a good proposal for changing this.  Maybe showing the Introduction heading would help, or using the same capitalization as in the h1.

> This article briefly:
> * explains the distinctions and overlaps between accessibility, usability, and inclusive design,
> * points out the importance of maintaining the focus of accessibility on people with disabilities, and
> * encourages increased coordination across accessibility, usability, and inclusion practices.

I wonder if we really need to spell out the three areas covered by the document in bullet 1 and 3, and if it wouldn’t be more significant to end on the maintaining the focus of accessibility on people with disabilities?

What about something like this?

> This article briefly:
> * explains the distinctions and overlaps between the three aspects,
> * encourages increased coordination across them, and
> * points out the importance of maintaining the focus of accessibility on people with disabilities.

**Comment by nitedog** [comment]
(would have been good to split this into two separate comments)

Regarding first sentence: I'd like EOWG input on this.

Regarding the order in the list, I changed it to:

> - explains the distinctions and overlaps between accessibility, usability, and inclusive design,
> - encourages increased coordination across research and practice in these disciplines, and,
> - points out the importance of maintaining the focus of accessibility on people with disabilities.

I think keeping the three terms is important in the first bullet (otherwise it is rather ambiguous), but agree it can be removed from the following bullets.

**Comment by bakkenb** [comment]
I like that version @nitedog. 

On the first issue, I am okay with the words repeating from the title.

**Comment by shawna-slh** [comment]
1. First sentence.
Respectfully disagree. That's just proper and clear writing. ;-) I strongly support leaving the first words in the first sentence as they are. I don't think we want to show the Intro heading - that adds unnecessary stuff. I definitely don't want to capitalize the words in the sentence - it's just not right. :)

2. Order of bullets.
I minorly disagree with changing the order of the bullets. "This article briefly:..." is a summary of the content of the article. The bullets should be in the order of the information in the document.

**Comment by nitedog** [comment]
@slhenry - these arguments don't really appear in a particular order in the document, so it is a summary anyway. I think the re-ordering makes more sense as it stands now.

@yatil - is this sufficient feedback for you to close this issue, or do you want more discussion on it?

**Comment by yatil** [comment]
All good for me!
