### ISSUE TITLE
[minor, ed’s discretion, nit-picky, sorry] ISO number

### ISSUE THREAD

**Issue by yatil** [w3c/wai-inclusion#29]
> Thus accessibility and usability overlap significantly. According to ISO 9241-11, usability is defined as the "extent to which a product can be used by specified users to achieve specified goals effectively, efficiently and with satisfaction in a specified context of use". This could address accessibility when "specified users" includes people with a range of disabilities and "specified context of use" includes accessibility considerations such as assistive technologies. However, the needs of people with disabilities are often not sufficiently addressed in usability practice and research.

Not the biggest fan of leading a sentence with an ISO number (but I know some usability people really like them). What about:

> Thus accessibility and usability overlap significantly. Usability is defined as the "extent to which a product can be used by specified users to achieve specified goals effectively, efficiently and with satisfaction in a specified context of use" (ISO 9241-11). This could address accessibility when "specified users" includes people with a range of disabilities and "specified context of use" includes accessibility considerations such as assistive technologies. However, the needs of people with disabilities are often not sufficiently addressed in usability practice and research.

**Comment by nitedog** [comment]
The sentence is not leading with an ISO number. In fact, I think your edit makes the ISO definition more authoritative that it may actually be. Saying "according to ISO" limits the definition to ISO only. Saying only "usability is defined as" implies that the definition is more widely recognized than it may seem. Please re-open if you feel this needs more discussion.
