### ISSUE TITLE
[minor, ed’s discretion, nit-picky, sorry] bulleted list styles

### ISSUE THREAD

**Issue by yatil** [w3c/wai-inclusion#30]
> Several accessibility requirements also benefit people and situations that are a focus of inclusive design. For example, Web Accessibility Benefits People With and Without Disabilities describes accessibility benefits for:
> * people with low literacy or not fluent in the language
> * people with low bandwidth connections or using older technologies
> * new and infrequent users
> * mobile device users

The first bulleted list on the page uses commas and “, and” at the end to form a complete sentence while this list does not. There might be a reason for using a different style that I’m not aware of, but if there isn’t I’m all for some consistency.

**Comment by nitedog** [comment]
Agreed, thanks.
