### ISSUE TITLE
[minor, ed’s discretion, nit-picky, sorry] Unsure about paragraph

### ISSUE THREAD

**Issue by yatil** [w3c/wai-inclusion#31]
> There are guidelines, standards, and techniques, such as the Web Content Accessibility Guidelines (WCAG), which is the international standard ISO/IEC 40500. Yet when designers, developers, and project managers approach accessibility as a checklist to meet standards, the focus is only on the technical aspects of accessibility, and the human interaction aspect is often lost, and accessibility is not achieved.

This paragraph reads somewhat backwards, the first sentence is not coherent with the following. The second sentence is also very long and splitting it up into two might make it easier to understand.

> There are guidelines, standards, and techniques, such as the Web Content Accessibility Guidelines (WCAG), which is the international standard ISO/IEC 40500. <del>Yet w</del><ins>W</ins>hen designers, developers, and project managers approach accessibility as a checklist to only meet  the standards, the focus shifts to the technical aspects of accessibility. As a result, the human interaction aspect is often lost, and accessibility is not achieved.

**Comment by nitedog** [comment]
I made some edits to improve the flow and shorten the second sentence. However, I think the overall order and the "yet" are important. Please re-open if your concern is not addressed.
