### ISSUE TITLE
[minor, ed’s discretion, nit-picky, sorry] accessible user experience (UX)

### ISSUE THREAD

**Issue by yatil** [w3c/wai-inclusion#32]
> accessible user experience (UX)

Should either be 

> accessible user experience (Accessible UX)

or 

> accessible user experience (AUX)

to include accessible in the abbreviation.

**Comment by nitedog** [comment]
Hmmm. "UX" is a commonly recognized acronym. "Accessible UX" seems unnecessarily repetitive and I'm not sure if "AUX" is a common acronym. Happy to get other opinions.

**Comment by bakkenb** [comment]
I don't think it would be good to introduce AUX. Already used for the term Auxiliary.

I would recommend dropping the "(UX)" as I don't think it is needed here.

**Comment by shawna-slh** [comment]
I vote for no abbreviation at all. Second choice would be leave it as "accessible user experience (UX)"
(and for closing this issue:)

**Comment by yatil** [comment]
I step back from my comment and support either using accessible user experience with or without (UX).
