### ISSUE TITLE
[Accessibility, Usability, and Inclusion] Intro

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-inclusion#4]
This is a comment related to the page [Accessibility, Usability, and Inclusion](//w3c.github.io/wai-inclusion/index.html)

Suggested edit to opening paragraph:
Accessibility, usability, and inclusion are closely related and overlap significantly. As a result, these considerations are most effectively addressed together, such as when designing and developing websites and applications. While practitioners should understand that each aspect may have somewhat different requirements and standards, a holistic approach leads to a more accessible, usable, and inclusive web for everyone.

**Comment by nitedog** [comment]
Took a pass, please re-open issue if not adequately addressed.
