### ISSUE TITLE
[Accessibility, Usability, and Inclusion] Context

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-inclusion#5]
This is a comment related to the page [Accessibility, Usability, and Inclusion](//w3c.github.io/wai-inclusion/index.html)

The context section is too long, we are constructing another wall of text.  Need iconography or fewer words or both. 

Also, what is the significance of having the three in rust and the fourth "Inclusive Design" in black? Seems odd, a bit distracting. Suggested edits:
Make the "Context" heading as is and then significantly shorten the three scoping statements and make them bullets:
- Accessibility -  addresses discriminatory aspects related to equivalent user experience for people with disabilities, including people with age-related impairments. For the Web, accessibility means that people with disabilities can perceive, understand, navigate, and interact with websites and tools, and that they can contribute equally without barriers. Further background is provided in the introduction to web accessibility.
- Usability - is about designing products to be effective, efficient, and satisfying for the target audience of the product. In essence this would include user experience for people with disabilities but usability guidance and tools often neglect accessibility considerations. <link to detail>
- Inclusion - is concerned with ensuring access for everyone, and that nobody is left behind. This includes broad aspects such as connectivity (to electricity and the internet), computer skills and literacy, language support, and affordability of hardware and software, as well as access for people with disabilities. <link to detail>

The final paragraph (not bulleted) could then be a much shorter note about Inclusive Design. Something like:
There are also common references in this context to universal design or design for all. These concepts involve designing products, such as websites, to allow their use by the broadest audience possible. Accessibility addresses many aspects of inclusive design on the Web, which is why it is sometimes considered to be a synonym. However, accessibility alone does not address all aspects of inclusive web design, such as for language support and mobile design.

**Comment by nitedog** [comment]
Thank you for these suggestions @sharronrush !
One issue is that this text describes what the terms are, but not what they are _not_. I think it is quite important to also distinguish between these terms. We often get questions and hear about confusion between these terms. I will try to abbreviate these "not" statements and see what it looks like. Let me know if you have other thoughts.

**Comment by nitedog** [comment]
Took a pass, please re-open issue if not adequately addressed.
