### ISSUE TITLE
[Accessibility, Usability, and Inclusion] Accessible Design

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-inclusion#6]
This is a comment related to the page [Accessibility, Usability, and Inclusion](//w3c.github.io/wai-inclusion/index.html)

I think most of this section should be removed and linked to elsewhere.

An approach might be to leave the first paragraph (maybe take one more pass for brevity) and then, the subheadings significantly decreased, something like this:

Usable Accessibility
Can the bulleted detail be moved to another page, leaving a general description and then <link to more>?

Real People
The first two paragraphs are sufficient. I would suggest removing everything starting with "Usability efforts..." since most of that info is in the linked pages.

**Comment by nitedog** [comment]
Took a pass, please re-open issue if not adequately addressed.
