### ISSUE TITLE
Overall & Key Points

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-inclusion#8]
It's getting better, but the overall organization and flow still isn't quite right. For example:
- The two main headings are "Inclusive Design" and "Accessible Design" – so it makes them seem like they are two different things that this document compares.
- I'm not sure how much "Usability" in considered an aspect of "Inclusive Design" – it doesn’t feel like the 3 bullets fit under the heading of "Inclusive Design".
- In the first paragraph under "Inclusive Design", I think it should list the broader issues, not just disability, and maybe not have the example that is disability-related. Rationale: We're trying to distinguish between inclusion/inclusive design and accessibility/accessible design so it adds confusion to have only a disability example in that first paragraph about inclusive design.
- The first paragraph under "Accessible Design", says; "… other design considerations, such as for internationalization, …" and I think that has a similar problem. Other considerations such as i18n should be mentioned under "Inclusive Design" _not_  "Accessible Design".
- I miss the point about _why_ it is sometimes important to differentiate – which was in a previous version of the intro.
- I think the Requirements are very good now. I think the document should more explicitly address the Goals in the Audience section -- probably to even state them (e.g., example, https://www.w3.org/WAI/EO/Drafts/access-use/accessibility-n-usability.html clearly states: "The purpose of this document is to…" and uses headings "Including Accessibility in Usability Research and Practice" and "Including Usability in Accessibility Research and Practice" – not that we want to do it like that, but at least it was clear :-)

And a couple of specifics:
- Avoid "which is why it is sometimes considered to be a synonym" since we assert that it is _not_ – someone might not catch the "However" after it. (The whole avoid-stating-the-myth issue.)
- An example of editing needed is last sentence of first paragraph. :-)

**Comment by nitedog** [comment]
Should be all addressed in the latest version, please re-open if needed.
